check:
  disabled_extensions: false
  interval_days: 1
fetch:
  url: ''
  max_attempts: 2
  timeout: 30
notification:
  emails:
<<<<<<< HEAD
    - jose.jimenez@wunderkraut.com
=======
    - pontus.nilsson@wunderkraut.com
>>>>>>> a952e0b607063ac5302ba86adbd4f5998d125af8
  threshold: all
